version: '3'
services:
  vsftpd:
    image: fauria/vsftpd
    ports:
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - /home/vagrant/ftp:/home/vsftpd/user
    environment:
      - FTP_USER=user
      - FTP_PASS=123
      - PASV_ADDRESS=192.168.100.3
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110
    restart: always
