#!/bin/bash

# Script de comandos para la práctica de Docker Compose
# Ejecutar en la VM servidorUbuntu

echo "=== PRÁCTICA DOCKER COMPOSE ==="
echo ""

echo "1. VERIFICAR VERSIÓN DE DOCKER COMPOSE"
docker compose version
echo ""

echo "2. CONFIGURAR VIM PARA YAML"
cp /vagrant/.vimrc ~/.vimrc
echo "Archivo .vimrc copiado al home del usuario"
echo ""

echo "3. EJEMPLO BÁSICO: NGINX + REDIS"
echo "Navegar a dockerComposeTest:"
echo "cd /vagrant/dockerComposeTest/"
echo ""
echo "Validar configuración:"
echo "docker compose config"
echo ""
echo "Ejecutar servicios:"
echo "sudo docker compose up -d"
echo ""
echo "Verificar estado:"
echo "sudo docker compose ps"
echo ""
echo "Escalar database a 4 instancias:"
echo "sudo docker compose up -d --scale database=4"
echo ""
echo "Verificar con docker ps:"
echo "sudo docker ps"
echo ""
echo "Detener servicios:"
echo "sudo docker compose down"
echo ""

echo "4. APLICACIÓN FLASK + MYSQL"
echo "Navegar a docker-tutorial:"
echo "cd /vagrant/docker-tutorial/"
echo ""
echo "Ejecutar aplicación:"
echo "sudo docker compose up -d"
echo ""
echo "Verificar en navegador: http://192.168.100.3:5000"
echo ""
echo "Instalar cliente MySQL:"
echo "sudo apt-get update"
echo "sudo apt-get install mysql-client"
echo ""
echo "Conectar a base de datos:"
echo "mysql --host=127.0.0.1 --port=32000 -u root -p"
echo "(Password: root)"
echo ""
echo "Detener aplicación:"
echo "sudo docker compose down"
echo ""

echo "5. SERVIDOR FTP"
echo "Preparar directorio:"
echo "sudo mkdir -p /home/vagrant/ftp"
echo "sudo chmod 777 /home/vagrant/ftp"
echo ""
echo "Detener vsftpd del host (si existe):"
echo "sudo service vsftpd stop"
echo ""
echo "Navegar a ftp-server:"
echo "cd /vagrant/ftp-server/"
echo ""
echo "Ejecutar servidor FTP:"
echo "sudo docker compose up -d"
echo ""
echo "Probar conexión FTP:"
echo "ftp 192.168.100.3"
echo "Usuario: user"
echo "Contraseña: 123"
echo ""
echo "Detener servidor:"
echo "sudo docker compose down"
echo ""

echo "=== FIN DEL SCRIPT ==="
echo "Todos los archivos están listos en /vagrant/"
