# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.hostname = "jupyter-server"
  config.vm.network :private_network, ip: "192.168.100.10"
  
  # Port forwarding para acceder a Jupyter desde el host
  config.vm.network "forwarded_port", guest: 8888, host: 8888, host_ip: "127.0.0.1"
  
  # Configuración de recursos
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end

  config.vm.provision "shell", path: "install_jupyter.sh"
end
